Q1: Create a list of 7 numbers. Print only the even numbers from the list.

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8]
even_numbers = []
for n in numbers:
  if n%2==0:
    even_numbers.append(n)
print(f"list of all even numbers: {even_numbers}")

list of all even numbers: [2, 4, 6, 8]

Q2: Create a list of 5 student names. Ask the user to input a name, and check if it exists in the
list. Print &quot;Found&quot; or &quot;Not Found&quot;.

In [ ]:
Name_list=["Ali","Imran","Ayyan","Burhan","Hanan"]
Corect_Name=input("enter the name")
if Corect_Name in Name_list:
    print("Found")
else:
    print("Not Found")

enter the nameBurhan
Found

Q3: Create a list of 6 numbers. Print the maximum and minimum numbers without using max()
and min() functions.

In [ ]:
numbers = [23, 65, 42, 78, 94, 22]
maximum = numbers[0]
minimum = numbers[0]
for i in numbers:
    if i > maximum:
      maximum = i
    if i < minimum:
      minimum =i

print(f"Maximum number in list: {maximum}")
print(f"Minimum number in list: {minimum}")

Maximum number in list: 94
Minimum number in list: 22

Q4: Create a list [2, 4, 6, 8, 10]. Multiply each number by 3 and store the results in a new
list. Print the new list.

In [ ]:
list=[2,4,6,8,10]
New_list=[]
for i in list:
  New_list.append(i*3)
print(f"New list: {New_list}")

New list: [6, 12, 18, 24, 30]

Q5: Create a nested list:
students = [[&quot;Ali&quot;, 20], [&quot;Sara&quot;, 22], [&quot;Ahmed&quot;, 19]]
Print only the names of the students.

In [ ]:
list=[["Ali", 20], ["Sara", 22], ["Ahmed", 19]]
for i in list:
  print(i[0])

Ali
Sara
Ahmed

Q6: Create a list of numbers. Find and print the second largest number from the list.

In [5]:
list=[20,65,87,45,91,55,82,54,10]
list.sort()
print(f"second largest number: {list[-2]}")

second largest number: 87

Q7: Create a list of numbers [1,2,3,4,5,6,7,8,9]. Print only the numbers at odd indexes (1,
3, 5 â€¦).

In [ ]:
list=[1,2,3,4,5,6,7,8,9]
odd_number=[]
for i in list:
  if i%2!=0:
    odd_number.append(i)
print(f"odd numbers: {odd_number}")

odd numbers: [1, 3, 5, 7, 9]

Q8: Create a list of words. Join them into a single sentence (string) separated by spaces and print
it.

In [ ]:

words_list = ["This", "is", "a", "beautiful", "Car", "."]
sentence =" ".join(words_list)
print(sentence)

This is a beautiful Car .