Q1: Create a dictionary with 3 fruits and their prices. Print the price of one fruit.

In [ ]:
dict={"apple":25,"banana":30,"orange":40}
print(f"The price of fruit is ={dict["banana"]}")

The price of fruit is =30

Q2: Make a dictionary of 3 students with their names as keys and marks as values. Print all the
keys (names).

In [ ]:
my_dicts={"Burhan":56,"Ayyan":72,"Hanan":68}
print(my_dicts.keys())

dict_keys(['Burhan', 'Ayyan', 'Hanan'])

Q3: Create a dictionary of 5 countries and their capitals. Ask the user to input a country and print
its capital.

In [ ]:

Dicts={"pakistan":"Islamabad","United States":"Washington","United Kingdom":"London","Germany":"Berlin"}
Country_Name=input("enter the country name")
print(f"The capital of {Country_Name} is {Dicts[Country_Name]}")

enter the country nameUnited Kingdom
The capital of United Kingdom is London

Q4: Create a dictionary with numbers as keys and their squares as values (for numbers 1 to 5).

In [ ]:
dics={1:1,2:4,3:9,4:16,5:25}
key=int(input("enter the key"))
print(f"The square of {key} is {dics[key]}")

enter the key3
The square of 3 is 9

Q5: Create a dictionary of a person with keys: name, age, city. Change the city to another one
and print the updated dictionary.

In [ ]:
Dic={"Name":"Burhan","Age":12,"City":"Lahore"}
Dic["City"]="Bahawalpur"
print(f"Updated Dic :{Dic}")

Updated Dic :{'Name': 'Burhan', 'Age': 12, 'City': 'Bahawalpur'}

Q6: Create a dictionary of items in a store with their quantities. Add a new item to the dictionary
and print it.

In [1]:
dict={"apple": 10, "banana": 20, "orange": 15}
dict["grapes"] = 25
print(f"Updated dictionary: {dict}")

Updated dictionary: {'apple': 10, 'banana': 20, 'orange': 15, 'grapes': 25}

Q7: Create a dictionary of student marks. Find and print the student with the highest marks.

In [5]:
dict={"Burhan":56,"Ayyan":72,"Hanan":68}
max_marks=max(dict.values())
print(f"Maximum Marks={max_marks}")

Maximum Marks=72

Q8: Make a nested dictionary:
students = {
&quot;Ali&quot;: {&quot;age&quot;: 20, &quot;grade&quot;: &quot;A&quot;},
&quot;Sara&quot;: {&quot;age&quot;: 22, &quot;grade&quot;: &quot;B&quot;}}
Print only the grades of all students.

In [18]:
students = { "Burhan": {"age": 20, "grade": "A"}, "Ayyan": {"age": 22, "grade": "B"},"Hanan":{"age":15,"grade":"C"}}

for i in students.values():
  print(i["grade"])

A
B
C

Q9: Create a dictionary and remove one key-value pair using pop(). Print the updated
dictionary.

In [21]:
dict={"apple": 10, "banana": 20, "orange": 15}
delet=dict.pop("banana")
print(f"updated dict:{dict}")

updated dict:{'apple': 10, 'orange': 15}